// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// PDE_Kernel
NumericVector PDE_Kernel(NumericVector DataVector, NumericVector DomainX, double PR, int NSeq, int NData);
RcppExport SEXP _DataVisualizations_PDE_Kernel(SEXP DataVectorSEXP, SEXP DomainXSEXP, SEXP PRSEXP, SEXP NSeqSEXP, SEXP NDataSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type DataVector(DataVectorSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type DomainX(DomainXSEXP);
    Rcpp::traits::input_parameter< double >::type PR(PRSEXP);
    Rcpp::traits::input_parameter< int >::type NSeq(NSeqSEXP);
    Rcpp::traits::input_parameter< int >::type NData(NDataSEXP);
    rcpp_result_gen = Rcpp::wrap(PDE_Kernel(DataVector, DomainX, PR, NSeq, NData));
    return rcpp_result_gen;
END_RCPP
}
// c_pde
Rcpp::NumericVector c_pde(Rcpp::NumericVector kernels, int nKernels, double paretoRadius, Rcpp::NumericVector DataPlus);
RcppExport SEXP _DataVisualizations_c_pde(SEXP kernelsSEXP, SEXP nKernelsSEXP, SEXP paretoRadiusSEXP, SEXP DataPlusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type kernels(kernelsSEXP);
    Rcpp::traits::input_parameter< int >::type nKernels(nKernelsSEXP);
    Rcpp::traits::input_parameter< double >::type paretoRadius(paretoRadiusSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type DataPlus(DataPlusSEXP);
    rcpp_result_gen = Rcpp::wrap(c_pde(kernels, nKernels, paretoRadius, DataPlus));
    return rcpp_result_gen;
END_RCPP
}
// c_pde_fast
Rcpp::NumericVector c_pde_fast(Rcpp::NumericVector kernels, int nKernels, double paretoRadius, NumericVector DataPlus);
RcppExport SEXP _DataVisualizations_c_pde_fast(SEXP kernelsSEXP, SEXP nKernelsSEXP, SEXP paretoRadiusSEXP, SEXP DataPlusSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type kernels(kernelsSEXP);
    Rcpp::traits::input_parameter< int >::type nKernels(nKernelsSEXP);
    Rcpp::traits::input_parameter< double >::type paretoRadius(paretoRadiusSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type DataPlus(DataPlusSEXP);
    rcpp_result_gen = Rcpp::wrap(c_pde_fast(kernels, nKernels, paretoRadius, DataPlus));
    return rcpp_result_gen;
END_RCPP
}
// c_quantile
Rcpp::NumericVector c_quantile(Rcpp::NumericVector x, Rcpp::NumericVector probs, int sorted);
RcppExport SEXP _DataVisualizations_c_quantile(SEXP xSEXP, SEXP probsSEXP, SEXP sortedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type probs(probsSEXP);
    Rcpp::traits::input_parameter< int >::type sorted(sortedSEXP);
    rcpp_result_gen = Rcpp::wrap(c_quantile(x, probs, sorted));
    return rcpp_result_gen;
END_RCPP
}
// get_edges
List get_edges(Rcpp::NumericMatrix AdjacencyMatrix, Rcpp::NumericVector x_vertex, Rcpp::NumericVector y_vertex);
RcppExport SEXP _DataVisualizations_get_edges(SEXP AdjacencyMatrixSEXP, SEXP x_vertexSEXP, SEXP y_vertexSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type AdjacencyMatrix(AdjacencyMatrixSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x_vertex(x_vertexSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y_vertex(y_vertexSEXP);
    rcpp_result_gen = Rcpp::wrap(get_edges(AdjacencyMatrix, x_vertex, y_vertex));
    return rcpp_result_gen;
END_RCPP
}
// quantile4LargeVectors
Rcpp::NumericVector quantile4LargeVectors(Rcpp::NumericVector x, Rcpp::NumericVector probs);
RcppExport SEXP _DataVisualizations_quantile4LargeVectors(SEXP xSEXP, SEXP probsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type probs(probsSEXP);
    rcpp_result_gen = Rcpp::wrap(quantile4LargeVectors(x, probs));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DataVisualizations_PDE_Kernel", (DL_FUNC) &_DataVisualizations_PDE_Kernel, 5},
    {"_DataVisualizations_c_pde", (DL_FUNC) &_DataVisualizations_c_pde, 4},
    {"_DataVisualizations_c_pde_fast", (DL_FUNC) &_DataVisualizations_c_pde_fast, 4},
    {"_DataVisualizations_c_quantile", (DL_FUNC) &_DataVisualizations_c_quantile, 3},
    {"_DataVisualizations_get_edges", (DL_FUNC) &_DataVisualizations_get_edges, 3},
    {"_DataVisualizations_quantile4LargeVectors", (DL_FUNC) &_DataVisualizations_quantile4LargeVectors, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_DataVisualizations(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
