# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_inPSphere2D <- function(data, xBinNr, yBinNr, nrXBins, nrYBins, nrData, paretoRadius) {
    .Call(`_DataVisualizations_c_inPSphere2D`, data, xBinNr, yBinNr, nrXBins, nrYBins, nrData, paretoRadius)
}

c_quantile <- function(x, probs) {
    .Call(`_DataVisualizations_c_quantile`, x, probs)
}

