# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

c_pde <- function(kernels, nKernels, paretoRadius, DataPlus) {
    .Call(`_DataVisualizations_c_pde`, kernels, nKernels, paretoRadius, DataPlus)
}

c_quantile <- function(x, probs, sorted = 0L) {
    .Call(`_DataVisualizations_c_quantile`, x, probs, sorted)
}

